/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoctorMain;

import DoctorForm.Doctor_FormAccount;
import DoctorForm.Doctor_FormAppointment;
import DoctorForm.Doctor_FormDashboard;
import DoctorForm.Doctor_FormHistory;
import DoctorForm.Doctor_FormHome;
import DoctorForm.Doctor_FormLogOut;
import java.awt.Color;
import javax.swing.JComponent;
import DoctorEvent.DoctorEventMenuSelected;

/**
 *
 * @author My PC
 */
public class Main extends javax.swing.JFrame {

    // Data members
    private Doctor_FormHome doctor_FormHome;
    private Doctor_FormAccount doctor_FormAccount;
    private Doctor_FormAppointment doctor_FormAppointment;
    private Doctor_FormDashboard doctor_FormDashboard;
    private Doctor_FormHistory doctor_FormHistory;
    private Doctor_FormLogOut doctor_FormLogOut;

    public Main() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        doctorMenu1.initMoving(Main.this);
        doctor_FormHome = new Doctor_FormHome();
        doctor_FormAccount = new Doctor_FormAccount();
        doctor_FormAppointment = new Doctor_FormAppointment();
        doctor_FormDashboard = new Doctor_FormDashboard();
        doctor_FormHistory = new Doctor_FormHistory();
        doctor_FormLogOut = new Doctor_FormLogOut();
        doctorMenu1.addEventMenuSelected(new DoctorEventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(doctor_FormDashboard);
                } else if (index == 1) {
                    setForm(doctor_FormAccount);
                } else if (index == 2) {
                    setForm(doctor_FormAppointment);
                } else if (index == 3) {
                    setForm(doctor_FormHistory);
                } else if (index == 8) {
                    setForm(doctor_FormLogOut);
                }
            }

        });
        setForm(doctor_FormDashboard);
        this.setVisible(true);
    }

    public void setForm(JComponent com) {
        Patient_mainPanel.removeAll();
        Patient_mainPanel.add(com);
        Patient_mainPanel.repaint();
        Patient_mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pateintBorderPanel1 = new DoctorSwing.DoctorBorderPanel();
        Patient_mainPanel = new javax.swing.JPanel();
        patientHeader2 = new DoctorComponent.DoctorHeader();
        doctorMenu1 = new DoctorComponent.DoctorMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }

            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pateintBorderPanel1.setBackground(new java.awt.Color(238, 234, 234));

        Patient_mainPanel.setOpaque(false);
        Patient_mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pateintBorderPanel1Layout = new javax.swing.GroupLayout(pateintBorderPanel1);
        pateintBorderPanel1.setLayout(pateintBorderPanel1Layout);
        pateintBorderPanel1Layout.setHorizontalGroup(
                pateintBorderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pateintBorderPanel1Layout.createSequentialGroup()
                                .addComponent(doctorMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(pateintBorderPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Patient_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(patientHeader2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 877,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))));
        pateintBorderPanel1Layout.setVerticalGroup(
                pateintBorderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pateintBorderPanel1Layout.createSequentialGroup()
                                .addComponent(patientHeader2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Patient_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 493,
                                        Short.MAX_VALUE))
                        .addComponent(doctorMenu1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pateintBorderPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pateintBorderPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed

    }// GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }// GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Patient_mainPanel;
    private DoctorComponent.DoctorMenu doctorMenu1;
    private DoctorSwing.DoctorBorderPanel pateintBorderPanel1;
    private DoctorComponent.DoctorHeader patientHeader2;
    // End of variables declaration//GEN-END:variables
}
