package Duc.PaymentForm;

import java.awt.EventQueue;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import Duc.Payment.Payment;
import Duc.Payment.PaymentDAO;
import Duc.Payment.PaymentManager;

public class PaymentForm extends javax.swing.JDialog {
    SimpleDateFormat dmy = new SimpleDateFormat("dd-MM-yyyy");
    SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
    Date date = new Date();
    String name;

    public PaymentForm() {
        initComponents();
        new JProgressBar().setIndeterminate(true);
    }

    public PaymentForm(java.awt.Frame parent, boolean modal, String name) {
        super(parent, modal);
        initComponents();
        this.name = name;
        fileData();
    }

    public PaymentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fileData();

    }

    public String getInsurance() {
        String insurance;
        if (rdoYes.isSelected()) {
            insurance = "yes";
        } else {
            insurance = "no";
        }
        return insurance;
    }

    public boolean validation() {
        boolean isValid = false;
        if (txtMoney.getText().isEmpty() || txtIllness.getText().isEmpty() || txtMedication.getText().isEmpty()
                || txaReport.getText().isEmpty()) {
            {
                JOptionPane.showMessageDialog(this, "Please enter both username and password.");
                isValid = false;
            }
            if (!rdoYes.isSelected() || !rdoNo.isSelected()) {
                isValid = false;
            }
            isValid = true;
        }
        return isValid;
    }

    public void getInformation() {

    }

    public void fileData() {
        txtDate.setText(dmy.format(date));
        txtTime.setText(time.format(date));
        txtName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glassIcon1 = new raven.glassmorphism.GlassIcon();
        glassIcon2 = new raven.glassmorphism.GlassIcon();
        glassIcon3 = new raven.glassmorphism.GlassIcon();
        glassIcon4 = new raven.glassmorphism.GlassIcon();
        rdoInsurance = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdoYes = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cboPayby = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIllness = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMedication = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReport = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btnSavePayment = new javax.swing.JButton();

        glassIcon1.setGlassIconConfig(new raven.glassmorphism.GlassIconConfig(
            "/glassicon/icon/card.svg", 5.0f, 0, 5,
            new java.util.HashMap<Integer, String>(){
                {
                    put(0,"@background");
                    put(1,"#6691a1");
                    put(2,"#6691a1");
                }
            },
            new raven.glassmorphism.GlassIconConfig.GlassShape(
                java.awt.Color.decode("#db214f"),
                new java.awt.geom.RoundRectangle2D.Double(2.0, 2.0, 10.0, 10.0, 5.0, 5.0),
                45.0f)
        ));

        glassIcon2.setGlassIconConfig(new raven.glassmorphism.GlassIconConfig(
            "/glassicon/icon/doc.svg", 5.0f, 1, 5,
            new java.util.HashMap<Integer, String>(){
                {
                    put(0,"#6691a1");
                    put(1,"@background");
                    put(2,"#6691a1");
                    put(3,"#6691a1");
                    put(4,"#6691a1");
                }
            },
            new raven.glassmorphism.GlassIconConfig.GlassShape(
                java.awt.Color.decode("#0ca064"),
                new java.awt.geom.RoundRectangle2D.Double(2.0, 2.0, 10.0, 10.0, 5.0, 5.0),
                45.0f)
        ));

        glassIcon3.setGlassIconConfig(new raven.glassmorphism.GlassIconConfig(
            "/glassicon/icon/currency.svg", 5.0f, 0, 5,
            new java.util.HashMap<Integer, String>(){
                {
                    put(0,"@background");
                    put(1,"#6691a1");
                    put(2,"#6691a1");
                }
            },
            new raven.glassmorphism.GlassIconConfig.GlassShape(
                java.awt.Color.decode("#9db035"),
                new java.awt.geom.RoundRectangle2D.Double(2.0, 2.0, 10.0, 10.0, 5.0, 5.0),
                45.0f)
        ));

        glassIcon4.setGlassIconConfig(new raven.glassmorphism.GlassIconConfig(
            "/glassicon/icon/dollar.svg", 5.0f, 0, 5,
            new java.util.HashMap<Integer, String>(){
                {
                    put(0,"@background");
                    put(1,"#6691a1");
                    put(2,"#6691a1");
                    put(3,"#6691a1");
                    put(4,"#6691a1");
                }
            },
            new raven.glassmorphism.GlassIconConfig.GlassShape(
                java.awt.Color.decode("#2ca6f3"),
                new java.awt.geom.RoundRectangle2D.Double(6.0, 7.0, 10.0, 10.0, 10.0, 10.0),
                45.0f)
        ));

        jButton2.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jButton2.setText("Change Mode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 35",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "split 2",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail",
                "span 2,al trail"
            }
        ));

        jLabel1.setText("Payment Details");
        crazyPanel1.add(jLabel1);

        jLabel2.setText("Infomation");
        crazyPanel1.add(jLabel2);
        crazyPanel1.add(jLabel3);
        crazyPanel1.add(jLabel7);
        crazyPanel1.add(jLabel8);

        jLabel5.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel5.setText("Name");
        crazyPanel1.add(jLabel5);

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        crazyPanel1.add(txtName);

        jLabel6.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel6.setText("Money");
        crazyPanel1.add(jLabel6);

        txtMoney.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        crazyPanel1.add(txtMoney);

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel4.setText("Insurance");
        crazyPanel1.add(jLabel4);

        rdoInsurance.add(rdoYes);
        rdoYes.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        rdoYes.setText("Yes");
        rdoYes.setEnabled(false);
        crazyPanel1.add(rdoYes);

        rdoInsurance.add(rdoNo);
        rdoNo.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        rdoNo.setText("No");
        rdoNo.setEnabled(false);
        crazyPanel1.add(rdoNo);

        jLabel9.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel9.setText("Method");
        crazyPanel1.add(jLabel9);

        cboPayby.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        cboPayby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa", "Momo", "Zalo Pay", "Paypal" }));
        crazyPanel1.add(cboPayby);

        jLabel10.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel10.setText("Date");
        crazyPanel1.add(jLabel10);

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        crazyPanel1.add(txtDate);

        jLabel11.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel11.setText("Time");
        crazyPanel1.add(jLabel11);

        txtTime.setEditable(false);
        txtTime.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        crazyPanel1.add(txtTime);

        jLabel12.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel12.setText("Illness");
        crazyPanel1.add(jLabel12);

        txtIllness.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        crazyPanel1.add(txtIllness);

        jLabel13.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel13.setText("Medication");
        crazyPanel1.add(jLabel13);

        txtMedication.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        crazyPanel1.add(txtMedication);

        jLabel14.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel14.setText("Report");
        crazyPanel1.add(jLabel14);

        txaReport.setColumns(20);
        txaReport.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        txaReport.setRows(5);
        jScrollPane1.setViewportView(txaReport);

        crazyPanel1.add(jScrollPane1);
        crazyPanel1.add(jLabel15);

        btnSavePayment.setBackground(new java.awt.Color(153, 204, 255));
        btnSavePayment.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        btnSavePayment.setText("Save");
        btnSavePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePaymentActionPerformed(evt);
            }
        });
        crazyPanel1.add(btnSavePayment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(480, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNameActionPerformed

    private void btnSavePaymentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSavePaymentActionPerformed
        // TODO add your handling code here:
        if (isValid()) {
            PaymentDAO paymentDAO = new PaymentDAO();
            PaymentManager paymentManager = new PaymentManager();
            String name = txtName.getText();
            String money = txtMoney.getText();
            String insurance = getInsurance();
            String method = (String) cboPayby.getSelectedItem();
            String date = txtDate.getText();
            String time = txtTime.getText();
            String illness = txtIllness.getText();
            String medication = txtMedication.getText();
            String report = txaReport.getText();
            Payment payment = new Payment(name, money, insurance, method, date, time, illness, medication, report);
            paymentManager.addPayment(payment);
            paymentDAO.savePayment(paymentManager.getListPayment());
        }

    }// GEN-LAST:event_btnSavePaymentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        if (!FlatLaf.isLafDark()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatMacDarkLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatMacLightLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("Duc.PaymentForm");
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                PaymentForm dialog = new PaymentForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePayment;
    private javax.swing.JComboBox<String> cboPayby;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private raven.glassmorphism.GlassIcon glassIcon1;
    private raven.glassmorphism.GlassIcon glassIcon2;
    private raven.glassmorphism.GlassIcon glassIcon3;
    private raven.glassmorphism.GlassIcon glassIcon4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rdoInsurance;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoYes;
    private javax.swing.JTextArea txaReport;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtIllness;
    private javax.swing.JTextField txtMedication;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
